const wordArray = [
    { word: "elephant", hint: "Large land mammal with a trunk" },
    { word: "sunflower", hint: "Yellow flower that follows the sun" },
    { word: "mountain", hint: "Tall natural elevation on Earth's surface" },
    { word: "keyboard", hint: "Input device for computers" },
    { word: "ocean", hint: "Vast body of saltwater" },
    { word: "guitar", hint: "Musical instrument with strings" },
    { word: "jungle", hint: "Dense, overgrown forest" },
    { word: "telescope", hint: "Optical instrument for viewing distant objects" },
    { word: "chocolate", hint: "Sweet, brown food made from cacao beans" },
    { word: "astronaut", hint: "Person trained for space travel" },
    { word: "bicycle", hint: "Two-wheeled human-powered vehicle" },
    { word: "moonlight", hint: "Light from the moon during the night" },
    { word: "fireplace", hint: "Structure for containing a fire indoors" },
    { word: "tornado", hint: "Violently rotating column of air" },
    { word: "camera", hint: "Device for capturing still or moving images" },
    { word: "sandcastle", hint: "Structure made of sand at the beach" },
    { word: "puzzle", hint: "A game or problem that tests one's ingenuity" },
    { word: "dictionary", hint: "Reference book containing words and definitions" },
    { word: "whale", hint: "Large marine mammal" },
    { word: "rainbow", hint: "Meteorological phenomenon with a spectrum of light" }
  ];